import AuthLayout from '../AuthLayout/AuthLayout';
import DashboardLayout from '../DashboardLayout/DashboardLayout';

export const metadata = {
  title: 'Layout',
  description: 'Generated by create next app',
};

const Layout = () => {
  const session = {
    isLogin: false,
    role: 'usersdsdf',
  };

  return session.isLogin ? (
    <DashboardLayout session={session} />
  ) : (
    <AuthLayout />
  );
};

export default Layout;
