// global styles
import 'react-phone-input-2/lib/style.css';
import './globals.css';
// antd
import AntdRegistry from '../lib/Antd/AntdRegistry';
// db connection
import dbConnect from '../lib/db/db.connect';
// toast
import Toast from '../ui/Toast/Toast.jsx';
// providers
import Providers from '../store/Providers';

//
export const dynamic = 'force-dynamic';

// Meta data
export const metadata = {
  title: 'Go Win',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  dbConnect();
  return (
    <html lang="en">
      <body>
        <main>
          <Toast />
          <AntdRegistry>
            <Providers>{children}</Providers>
          </AntdRegistry>
        </main>
      </body>
    </html>
  );
}
