// global styles
import 'react-phone-input-2/lib/style.css';
import './globals.css';
//
import AntdRegistry from '../lib/Antd/AntdRegistry';
// db connection
import dbConnect from '../lib/db/db.connect';
// toast
import Toast from '../ui/Toast/Toast.jsx';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Go Win',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  dbConnect();
  return (
    <html lang="en">
      <body>
        <main>
          <Toast />
          <AntdRegistry>{children}</AntdRegistry>
        </main>
      </body>
    </html>
  );
}
