// global styles
import 'react-phone-input-2/lib/style.css';
import './globals.css';
// antd
import AntdRegistry from '../lib/Antd/AntdRegistry';
// db connection
import dbConnect from '../lib/db/db.connect';
// toast
import Toast from '../ui/Toast/Toast.jsx';
// providers
import Providers from '../store/Providers';
import AuthSession from '../lib/AuthSession/AuthSession';
//
export const dynamic = 'force-dynamic';
export const fetchCache = 'force-no-store';
export const revalidate = 0;

// Meta data
export const metadata = {
  title: 'Go Win',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body className="bg-primary-blue" suppressHydrationWarning={true}>
        <main>
          <Toast />
          <AntdRegistry>
            <AuthSession>
              <Providers>{children}</Providers>
            </AuthSession>
          </AntdRegistry>
        </main>
      </body>
    </html>
  );
}
