import AuthLayout from '../components/AuthLayout/AuthLayout';

export const metadata = {
  title: 'Go win - Auth',
  description: 'Generated by create next app',
};

const Home = () => {
  return <AuthLayout />;
};

export default Home;
