import AuthLayout from '../components/AuthLayout/AuthLayout';

export const metadata = {
  title: 'Go win - Auth',
  description: 'Generated by create next app',
};

export const fetchCache = 'force-no-store';
export const dynamic = 'force-dynamic';

const Home = () => {
  return <AuthLayout />;
};

export default Home;
