import React from 'react';
export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};
const Dashboard = () => {
  return <div>dashboard</div>;
};

export default Dashboard;
